language: node_js
node_js:
  - 'node'
cache:
  npm: false
  directories:
    - '~/.pnpm-store'
before_install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
script:
  - pnpm run build
after_success:
  - cp build/index.html build/404.html
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GH_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master